<?php

declare(strict_types=1);

namespace Nowo\BlogKitBundle\DependencyInjection;

use Nowo\BlogKitBundle\Enum\BlogListingMode;
use Nowo\BlogKitBundle\Enum\BlogMasonryStrategy;
use Nowo\BlogKitBundle\Enum\BlogObjectAccessStrategy;
use Nowo\BlogKitBundle\Enum\CommentCaptchaStrategy;
use Nowo\BlogKitBundle\Enum\CommentRateLimitStrategy;
use Nowo\BlogKitBundle\Enum\CssFramework;
use Nowo\BlogKitBundle\Enum\HtmlSanitizeStrategy;
use Nowo\BlogKitBundle\Enum\IconSet;
use Nowo\BlogKitBundle\Enum\RowActionsDisplay;
use Symfony\Component\Config\Definition\Builder\ArrayNodeDefinition;
use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

/**
 * Validates and normalizes `nowo_blog_kit` configuration.
 */
final class Configuration implements ConfigurationInterface
{
    public const string ALIAS = 'nowo_blog_kit';

    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder(self::ALIAS);
        /** @var ArrayNodeDefinition $root */
        $root = $treeBuilder->getRootNode();

        $root
            ->children()
                ->scalarNode('user_class')
                    ->defaultNull()
                    ->info('FQCN of the host user entity implementing BlogUserInterface.')
                ->end()
                ->scalarNode('default_locale')->defaultValue('es')->end()
                ->arrayNode('locales')
                    ->scalarPrototype()->end()
                    ->defaultValue(['es', 'en'])
                ->end()
                ->arrayNode('security')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode('access_roles')
                            ->scalarPrototype()->end()
                            ->defaultValue(['ROLE_ADMIN'])
                            ->info('Grants every admin capability when any listed role is held (REQ-UI-002).')
                        ->end()
                        ->arrayNode('manage_roles')
                            ->scalarPrototype()->end()
                            ->defaultValue(['ROLE_EDITOR'])
                        ->end()
                        ->arrayNode('moderate_roles')
                            ->scalarPrototype()->end()
                            ->defaultValue(['ROLE_MODERATOR'])
                        ->end()
                        ->arrayNode('configure_roles')
                            ->scalarPrototype()->end()
                            ->defaultValue(['ROLE_ADMIN'])
                        ->end()
                        ->scalarNode('access_checker')->defaultNull()->end()
                        ->booleanNode('allow_unauthenticated')->defaultFalse()->end()
                        ->arrayNode('object_access')
                            ->addDefaultsIfNotSet()
                            ->info('Object-level checks after roles (e.g. editors only manage their publications).')
                            ->children()
                                ->enumNode('strategy')
                                    ->values(BlogObjectAccessStrategy::values())
                                    ->defaultValue(BlogObjectAccessStrategy::None->value)
                                    ->info('none (roles only), owner (createdBy), or service (host checker).')
                                ->end()
                                ->scalarNode('service')
                                    ->defaultNull()
                                    ->info('Service id implementing BlogKitResourceAccessCheckerInterface when strategy=service.')
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('web_ui')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('layout_template')
                            ->defaultValue('@NowoBlogKitBundle/admin/layout.html.twig')
                        ->end()
                        ->scalarNode('public_layout_template')
                            ->defaultValue('@NowoBlogKitBundle/public/layout.html.twig')
                        ->end()
                        ->enumNode('css_framework')
                            ->values(CssFramework::values())
                            ->defaultValue(CssFramework::Bootstrap5->value)
                        ->end()
                        ->enumNode('icon_set')
                            ->values(IconSet::values())
                            ->defaultValue(IconSet::BootstrapIcons->value)
                        ->end()
                        ->enumNode('row_actions_display')
                            ->values(RowActionsDisplay::values())
                            ->defaultValue(RowActionsDisplay::Icon->value)
                        ->end()
                        ->integerNode('page_size')
                            ->min(1)
                            ->max(200)
                            ->defaultValue(20)
                        ->end()
                        ->scalarNode('privacy_url')->defaultValue('#')->end()
                    ->end()
                ->end()
                ->arrayNode('doctrine')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('table_prefix')->defaultValue('')->end()
                        ->scalarNode('connection')->defaultValue('default')->end()
                    ->end()
                ->end()
                ->arrayNode('comments')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode('rate_limit')
                            ->addDefaultsIfNotSet()
                            ->info('Public comment POST rate limiting. Requires cache.app except strategy none/service.')
                            ->children()
                                ->enumNode('strategy')
                                    ->values(CommentRateLimitStrategy::values())
                                    ->defaultValue(CommentRateLimitStrategy::FixedWindow->value)
                                ->end()
                                ->integerNode('limit')
                                    ->min(0)
                                    ->defaultValue(5)
                                    ->info('Max submissions per interval. 0 disables the limiter.')
                                ->end()
                                ->integerNode('interval_seconds')
                                    ->min(0)
                                    ->defaultValue(60)
                                ->end()
                                ->scalarNode('service')
                                    ->defaultNull()
                                    ->info('Service id implementing BlogCommentRateLimiterInterface when strategy=service.')
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('captcha')
                            ->addDefaultsIfNotSet()
                            ->info('Public comment bot mitigation. Secrets stay in YAML, not BlogSettings.')
                            ->children()
                                ->enumNode('strategy')
                                    ->values(CommentCaptchaStrategy::values())
                                    ->defaultValue(CommentCaptchaStrategy::Honeypot->value)
                                ->end()
                                ->scalarNode('site_key')->defaultValue('')->end()
                                ->scalarNode('secret_key')->defaultValue('')->end()
                                ->floatNode('min_score')
                                    ->min(0)
                                    ->max(1)
                                    ->defaultValue(0.5)
                                    ->info('Minimum reCAPTCHA v3 score.')
                                ->end()
                                ->scalarNode('honeypot_field')->defaultValue('website')->end()
                                ->scalarNode('service')
                                    ->defaultNull()
                                    ->info('Service id implementing BlogCommentCaptchaStrategyInterface when strategy=service.')
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('listing')
                    ->addDefaultsIfNotSet()
                    ->info('Public /blog index: numbered pagination or infinite scroll.')
                    ->children()
                        ->enumNode('mode')
                            ->values(BlogListingMode::values())
                            ->defaultValue(BlogListingMode::Paginated->value)
                            ->info('paginated (numbered pages) or infinite (IntersectionObserver + ?partial=1).')
                        ->end()
                        ->arrayNode('masonry')
                            ->addDefaultsIfNotSet()
                            ->info('Public index card layout. Admin inherit / 0 keeps these YAML values.')
                            ->children()
                                ->enumNode('strategy')
                                    ->values(BlogMasonryStrategy::values())
                                    ->defaultValue(BlogMasonryStrategy::Masonry->value)
                                    ->info('masonry (packed columns), grid (uniform rows), or list (single column).')
                                ->end()
                                ->integerNode('columns_mobile')
                                    ->min(1)
                                    ->max(2)
                                    ->defaultValue(1)
                                ->end()
                                ->integerNode('columns_tablet')
                                    ->min(1)
                                    ->max(2)
                                    ->defaultValue(2)
                                ->end()
                                ->integerNode('columns_desktop')
                                    ->min(1)
                                    ->max(3)
                                    ->defaultValue(2)
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('html')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode('sanitize')
                            ->addDefaultsIfNotSet()
                            ->info('Sanitize article HTML on persist and public render. Default none keeps trusted-editor |raw.')
                            ->children()
                                ->enumNode('strategy')
                                    ->values(HtmlSanitizeStrategy::values())
                                    ->defaultValue(HtmlSanitizeStrategy::None->value)
                                ->end()
                                ->scalarNode('service')
                                    ->defaultNull()
                                    ->info('Service id implementing BlogHtmlSanitizerInterface when strategy=service.')
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end();

        return $treeBuilder;
    }
}
