nowo_blog_kit:
    user_class: App\Entity\User
    default_locale: es
    locales: [es, en]
    security:
        access_roles: [ROLE_ADMIN]
        manage_roles: [ROLE_ADMIN]
        moderate_roles: [ROLE_ADMIN]
        configure_roles: [ROLE_ADMIN]
        allow_unauthenticated: false
        # object_access:
        #     strategy: owner
    web_ui:
        layout_template: admin/layout.html.twig
        public_layout_template: base.html.twig
        css_framework: bootstrap5
        icon_set: bootstrap-icons
        row_actions_display: icon
    listing:
        mode: infinite
        masonry:
            strategy: masonry
            columns_mobile: 1
            columns_tablet: 2
            columns_desktop: 2
    comments:
        rate_limit:
            strategy: fixed_window
            limit: 5
            interval_seconds: 60
        captcha:
            strategy: honeypot
    html:
        sanitize:
            strategy: allowlist
    doctrine:
        table_prefix: ''
